config/routes.rb
KingAndCountry::Application.routes.draw do
  devise_for :users
  root 'pages#index'
  resources :users
  resources :countries
  resources :country_armies

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  validates_presence_of :country
  validates_presence_of :name
  has_many :users
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates_presence_of :name
  has_many :users,
    through: :country_armies
  has_many :country_armies
  has_many :cities
  before_create :generate_invite_token

  def generate_invite_token
    existing_tokens = Country.pluck(:invite_token)
    country_token = SecureRandom.hex(5)
    if existing_tokens.include?(country_token)
      generate_invite_token
    else
      self.invite_token = country_token
    end
  end

  def capital_city
    cities.where(capital_city: true).first
  end
end

app/models/country_army.rb
class CountryArmy < ActiveRecord::Base
  validates_presence_of :country
  validates_presence_of :user
  validates_presence_of :age
  belongs_to :user
  belongs_to :country

  class << self
    def current_age
      1
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :username
  has_many :countries,
    through: :country_armies
  has_many :country_armies
  belongs_to :city
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def current_country
    user_country = CountryArmy.where("age = ? AND user_id = ?",
     CountryArmy.current_age,
     self.id).first
    if user_country == nil
      false
    else
      user_country.country
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @user = current_user
    @user_country = CountryArmy.new
    @countries = Country.all
  end

  def create
    binding.pry
  end

end

app/controllers/country_armies_controller.rb
class CountryArmiesController < ApplicationController
  def create
    if params[:q]
      @country = Country.where(invite_token: params[:q]).first
    else
      @country = Country.find(params[:country_army][:country])
    end
    @user_country = CountryArmy.new(user: current_user,
      age: CountryArmy.current_age,
      country: @country)
    if @user_country.save
      redirect_to root_path, notice: "You are now part of #{@country.name}"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = params[:id]
  end

  def edit
    @user = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/countries/index.html.erb
<%= simple_form_for @user_country do |f| %>
  <%= f.input :country, label: 'Country', collection: @countries, as: :select %>
  <%= f.button :submit, 'Submit', id: 'submit_random_country' %>
<% end %>

<%= form_tag(country_armies_path, method: "post") do %>
  <%= label_tag(:q, "Country Code") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag "Submit", id: 'submit_country_code' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "King and Country" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to 'Sign Up', new_user_registration_path %>
    <%= link_to 'Sign In', new_user_session_path, id: 'sign_in' %>
    <% if user_signed_in? %>
      <%= link_to 'My Profile', user_path(current_user) , id: 'my_profile' %>
      <% if current_user.current_country %>
        <%= link_to 'City Center', country_city_path(current_user.current_country, current_user.city) %>
      <% else %>
        <%= link_to 'Join a Country', countries_path %>
      <% end %>
    <% end %>
    <div class="row">
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/show.html.erb
<%= link_to 'Edit Profile', edit_user_registration_path, id: 'edit_profile' %>